package com.projet_jee.E_healthcare.model;

public enum AdminRole {
    RECEPTIONIST, MEDICAL_SECRETARY, CLINIC_COORDINATOR, OFFICE_MANAGER,
    BILLING_SPECIALIST, MEDICAL_CODER, PATIENT_SERVICE_REPRESENTATIVE,
    SCHEDULING_COORDINATOR, HUMAN_RESOURCES_OFFICER, FINANCIAL_OFFICER,
    IT_SUPPORT_SPECIALIST, ADMINISTRATIVE_ASSISTANT, RECORDS_CLERK,
    INSURANCE_VERIFICATION_SPECIALIST, COMPLIANCE_OFFICER, MARKETING_COORDINATOR,
    INVENTORY_MANAGER, DATA_ENTRY_SPECIALIST, TRANSLATOR_INTERPRETER
}
