package com.projet_jee.E_healthcare.model;

public enum DoctorSpeciality {
    CARDIOLOGIST, PEDIATRICIAN, DERMATOLOGIST, ORTHOPEDIST, NEUROLOGIST,
    GYNECOLOGIST, PSYCHIATRIST, ONCOLOGIST, OPHTHALMOLOGIST, ENT_SPECIALIST,
    GENERAL_SURGEON, UROLOGIST, INTERNAL_MEDICINE, RHEUMATOLOGIST, ALLERGIST,
    EMERGENCY_MEDICINE, FAMILY_PHYSICIAN, ANESTHESIOLOGIST, RADIOLOGIST,
    PATHOLOGIST
}
