package com.projet_jee.E_healthcare.model;

public enum NurseSpeciality {
    CARDIAC_NURSE, PEDIATRIC_NURSE, ICU_NURSE, EMERGENCY_ROOM_NURSE,
    OPERATING_ROOM_NURSE, PSYCHIATRIC_NURSE, ONCOLOGY_NURSE, GERIATRIC_NURSE,
    NEONATAL_NURSE, ORTHOPEDIC_NURSE, PUBLIC_HEALTH_NURSE, NURSE_ANESTHETIST,
    NURSE_MIDWIFE, SCHOOL_NURSE, FAMILY_NURSE_PRACTITIONER, TRAVEL_NURSE,
    HOME_HEALTH_NURSE, RESEARCH_NURSE, DERMATOLOGY_NURSE, INFECTIOUS_DISEASE_NURSE;
}
